### ISSUE TITLE
Keyboard error

### ISSUE THREAD

**Issue by sam-pandey** [vlakhani28/vps-new#2]
I'm unable to type anything via anydesk.
I'm using anydesk in android how can I fix this issue??

**Comment by innowebka** [comment]
add latest python & pip version ?

**Comment by vlakhani28** [comment]
> I'm unable to type anything via anydesk.
> I'm using anydesk in android how can I fix this issue??

Why are you using anydesk? You can simply open it using any browser

**Comment by vlakhani28** [comment]
> add latest python & pip version ?

The latest versions of pip and python are already installed do tell me it it isn't working

**Comment by innowebka** [comment]
> 
> 
> > add latest python & pip version ?
> 
> The latest versions of pip and python are already installed do tell me it it isn't working

working ❤️

**Comment by innowebka** [comment]
can you add wine for installing exe ?

**Comment by sam-pandey** [comment]
> > I'm unable to type anything via anydesk.
> > I'm using anydesk in android how can I fix this issue??
> 
> Why are you using anydesk? You can simply open it using any browser

It's not enough good to use that in browser like i can't access that via phone i mean i can but can't use fluently


Is it possible to access this via vnc viewer??

**Comment by vlakhani28** [comment]
> can you add wine for installing exe ?

I will try adding it in some days

**Comment by vlakhani28** [comment]
> > > I'm unable to type anything via anydesk.
> > > I'm using anydesk in android how can I fix this issue??
> > 
> > 
> > Why are you using anydesk? You can simply open it using any browser
> 
> It's not enough good to use that in browser like i can't access that via phone i mean i can but can't use fluently
> 
> Is it possible to access this via vnc viewer??

Lemme check this out if we can access it using VNC Viewer

**Comment by sam-pandey** [comment]
> > > > I'm unable to type anything via anydesk.
> > > > I'm using anydesk in android how can I fix this issue??
> > > 
> > > 
> > > Why are you using anydesk? You can simply open it using any browser
> > 
> > 
> > It's not enough good to use that in browser like i can't access that via phone i mean i can but can't use fluently
> > Is it possible to access this via vnc viewer??
> 
> You can't really access a VPS using phone. Obviously you won't be able to use it fluently.

Is it possible to use via unc viewer if yes then it's awesome

**Comment by innowebka** [comment]
Ubuntu update 21.04 available so how to update it to 21.04 from 18.04 ?

**Comment by vlakhani28** [comment]
> Ubuntu update 21.04 available so how to update it to 21.04 from 18.04 ?

I have installed image of Ubuntu 18.04 if you want you can fork the repo and  change the docker file to Install the latest version of Ubuntu

**Comment by innowebka** [comment]
> 
> 
> > Ubuntu update 21.04 available so how to update it to 21.04 from 18.04 ?
> 
> I have installed image of Ubuntu 18.04 if you want you can fork the repo and change the docker file to Install the latest version of Ubuntu

tried but throws error so can you reply with docerfile codes?

**Comment by vlakhani28** [comment]
Its already present on the repo pls check

**Comment by innowebka** [comment]
please add wine
