### ISSUE TITLE
Account suspended

### ISSUE THREAD

**Issue by ghost** [vlakhani28/vps-new#4]
Hello,wth my account got suspended after deploying this. Please explain

**Comment by vlakhani28** [comment]
Yes i have clearly mentioned it no longer works on Heroku due to the change of guidelines

Alternative: https://github.com/vlakhani28/vps

**Comment by ghost** [comment]
oops I am late ):

**Comment by KendallDoesCoding** [comment]
> Yes i have clearly mentioned it no longer works on Heroku due to the change of guidelines
> 
> Alternative: https://github.com/vlakhani28/vps

What guideline does it break?

**Comment by vlakhani28** [comment]
It no longer allows users to deploy VMs. You can read the guidelines when deploying the VPS
